version: "3"
services:
  #PHP Service
  cast-api:
    container_name: cast-api
    build:
      context: .docker/php
      dockerfile: Dockerfile
    image: "cast/php-apache"
    ports:
      - 8080:80
    volumes:
      - ./backend/:/var/www/html
    networks:
      - cast
  #SQL Server Service
  cast-db:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
        - '.:/application'
    environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=desafio
        - MYSQL_USER=desafiousr
        - MYSQL_PASSWORD=desafiopswd
    ports:
        - '58002:3306'
    networks:
      - cast
  # SPA App
  cast-front:
    container_name: cast-app
    image: "cast/vue"
    build:
      context: .
      dockerfile: .docker/vue/Dockerfile
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    networks:
      - cast

# Docker Networks
networks:
  cast:
    driver: bridge
#Volumes
volumes:
  ms-sqlserver-data:
    driver: local
